window.onload = function(){

    alert("Welcome");
}

new Date().getFullYear();

 document.getElementById("date").innerHTML = new Date().getFullYear();

 function availability1 ()
{
   document.getElementById("stock").innerHTML = "OUT OF STOCK"
}
 function availability2 ()
{
   document.getElementById("stock2").innerHTML = "OUT OF STOCK"
}
 function availability3 ()
{
   document.getElementById("stock3").innerHTML = "OUT OF STOCK"
}
 function availability4 ()
{
   document.getElementById("stock4").innerHTML = "OUT OF STOCK"
}
 function availability5 ()
{
   document.getElementById("stock5").innerHTML = "OUT OF STOCK"
}